### ISSUE TITLE
[RFC] Tratamento para MergingEventHandler e ProxyingEventHandler

### ISSUE THREAD

**Issue by jabolina** [GuiaBolso/guiabolso-connector#11]
Esse texto é para iniciarmos uma discussão para encontrarmos uma maneira de tratar os erros que acontecem no `MergingEventHandler`, que trata os eventos criados pelo `data_packages.yaml` e o `ProxyingEventHandler` que realiza o proxy de eventos. Temos que chegar em uma solução que seja possível de mantermos e seja compatível com o funcionamento atual, iremos nos focar nos erros que o usuário não forneceu permissão para realizar uma consulta.

## Nomenclatura

- **Cliente**: quem utiliza a aplicação e realiza consultas;
- **Usuário**: pessoa que dá permissões para que cliente realize consultas;

## Problema

Com o funcionamento atual, os erros são retornados diretamente pela API, quando realizada só uma consulta e quando são eventos agregados seguem o formato descrito [na README](https://github.com/GuiaBolso/guiabolso-connector#eventos-agregadores-de-vari%C3%A1veis), exemplos do objeto retornado, respectivamente:

```json
{
  "name": "gbconnect:identification:variables:unauthorized",
  "version": 1,
  "id": "6218dd55-2e51-4aaa-8457-1997fda4b75d",
  "flowId": "d7f66b31-d70d-4c20-a6e1-948436742743",
  "payload": {
    "code": "EVENT_EXECUTION_DENIED",
    "parameters": {}
  },
  "identity": {},
  "auth": {},
  "metadata": {}
}
```
```json
{
  "name": "datapackage:aggregator:variables:response",
  "version": 1,
  "id": "af4d6013-2846-4fea-9c6f-ac4d5027bc6d",
  "flowId": "bb03fddb-a179-4574-8f6d-6725e3a7e1f4",
  "payload": {
    "variables": [
      {
        "key": "GBCONNECT.IDENTIFICATION.VARIABLES.STATUS",
        "value": "ERROR: EVENT_EXECUTION_DENIED",
        "type": "STRING"
      },
      {
        "key": "GBCONNECT.ACCOUNT.STATEMENTS.STATUS",
        "value": "ERROR: UNKNOWN_DISPATCH_ERROR",
        "type": "STRING"
      }
    ]
  },
  "identity": {},
  "auth": {},
  "metadata": {
    "cached": false
  }
}
```

Atualmente, com esse fluxo, dependendo do erro retornado o cliente pode tomar uma ação. Esse alteração visa especificamente os casos que o usuário não forneceu permissão, e retornaremos algum erro de maneira que o cliente possa direcionar o usuário pelo funil novamente e conceder as permissões necessárias.

## Funcionamento atual

Como temos que manter compatibilidade entre o funcionamento atual e o que criarmos, serão listados como está atualmente. Em um futuro, podemos depreciar a API de agregamento.

### Evento único

Quando chamamos um evento diretamente ou passando pelo `ProxyingEventHandler`, caso alguma falha aconteça o objeto já será diretamente retornado para o cliente que realizou a consulta, como o objeto pode ser visto acima. Esse funcionamento depende do cliente realizar o direcionamento do usuário caso aconteça algum erro de permissão, sendo responsabilidade do cliente tratar os códigos de erro corretamente e da maneira que melhor servir no seu caso de uso.

### Eventos agregados

Utilizando o agregador de eventos começamos a ter um comportamento diferenciado. Utilizando o `data_packages` podemos definir vários eventos diferentes, quando um desses eventos falha o erro não se propaga e são executadas as requisições para todos os eventos definidos. O agregador de eventos oferece a opção para realizar o cache das respostas obtidas, o que faz com que respostas de usuário sem permissão possam ser salvas em cache. 

Nesse comportamento, temos um cenário um pouco diferentes. Em um agregador com _n_ eventos onde somente um ou alguns falham, o cliente teria que percorrer a lista de variáveis e tratar os erros encontrados. Desses erros, algum pode ser de permissão, mas visto que outras requisições aconteceram com sucesso pode ser que o caso de uso do cliente não precise que o usuário passe novamente pelo funil, as informações obtidas já seriam suficientes. Assim também podemos ter um caso que devemos redirecionar o usuário para pedir as permissões necessárias.

## Sugestões para tratamentos

Essa seção serão listadas algumas sugestões de como podemos tratar esses casos. Para o que iremos construir devemos manter alguma compatibilidade com o que existe atualmente, levar em consideração cobranças e complexidade para mantermos.

### Flags de tratamentos

Assim como existem as flags para funcionamento do cache `NEVER, ONLY_ON_FAILURES, ALWAYS`, poderiamos criar flags para definir como será o tratamento do erro. Poderíamos seguir uma linha de opções como `REDIRECT_ON_UNAUTHORIZED = [NEVER, PROXYING_EVENTS, AGGREGATE_EVENTS, ALL]`, que são fornecidas como variáveis de ambiente para aplicação, nesse caso manter a compatibilidade com funcionamento atual seria mais fácil, pois com a flag desabilitada nada mudaria.

Mantendo um foco especial nos eventos agregados, devemos discutir uma maneira mais interessante de como tratar os erros de permissão. Caso a flag `AGGREGATE_EVENTS` esteja ativa, iremos tratar os erros que acontecerem nos eventos agregados, onde caso algum evento de falta de permissão aconteça, as chamadas para os outros eventos serão ignoradas e iremos propagar o erro de volta para o cliente, sugerindo um redirecionamento para usuário fornecer as permissões.

Algumas das perguntas que precisam ser respondidas nesse caso:

* Devemos seguir o mesmo objeto já existente e retornar o erro no array `variables` com restante dos eventos com status `IGNORED`?
* Devemos ter prioridade sobre a configuração de cache e retornar no primeiro erro ou executar todas requisições e retonar erro somente ao final?

Para o caso da utilização da flag `PROXYING_EVENTS`, caso ocorra algum problema de permissão iremos retornar um erro para redirecionamento, como acontece com [refresh token expirado](https://github.com/GuiaBolso/guiabolso-connector/blob/master/events/src/main/kotlin/br/com/guiabolso/connector/auth/EventAuthenticationService.kt#L31).

Caso esteja ativa a flag `NEVER`, que seria o valor padrão, o funcionamento atual se mantem sem nenhuma alteração. Caso esteja em `ALL` o tratamento irá ser aplicado em ambos eventos agregados e eventos do proxy.

### Documentar

Outra possibilidade seria somente dar um foco especial para esses casos na nossa documentação, dar sugestões de como proceder em casos que o usuário não concedeu permissão. Algo assim seria mais simples, mas não garante que o cliente irá seguir.

**Comment by Cleidiano** [comment]
> Devemos seguir o mesmo objeto já existente e retornar o erro no array variables com restante dos eventos com status IGNORED?

Não entendi essa dúvida aqui.

> Devemos ter prioridade sobre a configuração de cache e retornar no primeiro erro ou executar todas requisições e retronar erro somente ao final?

Essa feature deve ter precedência sobre cache configurado com a policy `ONLY_ON_FAILURE` já que elas são mutuamente exclusivas. As demais estrategias de cache acontecem antes mesmo de fazer a request então, já possuem precedência.

**Comment by jabolina** [comment]
Utilizando esse payload do exemplo o agregado seriam 2 eventos juntos, onde falhou com usuário não tendo permissão. Na aplicação temos uma [lista de futures](https://github.com/GuiaBolso/guiabolso-connector/blob/master/events/src/main/kotlin/br/com/guiabolso/connector/handlers/MergingEventHandler.kt#L54), que são as requisições sendo realizadas, quando uma das requisições falhar já abortariamos tudo para retornar o erro imediatamente caso seja de permissão?

Caso tudo seja abortado e apontamos diretamente qual erro aconteceu, o objeto retornado teria um formato como:

```json
{
    "name":"datapackage:aggregator:variables:unauthorized",
    "version":1,
    "id":"af4d6013-2846-4fea-9c6f-ac4d5027bc6d",
    "flowId":"bb03fddb-a179-4574-8f6d-6725e3a7e1f4",
    "payload":{
        "code":"EVENT_EXECUTION_DENIED",
        "parameters":{
            "origin":"gbconnect:identification:variables"
        }
    },
    "identity":{},
    "auth":{},
    "metadata":{}
}
```

Nessa abordagem já retornariamos diretamente qual o erro aconteceu e em qual evento foi gerado. Mas com isso retornamos um objeto totalmente diferente do que se tem acordado para API. Outra opção seria:

```json
{
    "name":"datapackage:aggregator:variables:response",
    "version":1,
    "id":"af4d6013-2846-4fea-9c6f-ac4d5027bc6d",
    "flowId":"bb03fddb-a179-4574-8f6d-6725e3a7e1f4",
    "payload":{
        "variables":[
            {
                "key":"GBCONNECT.IDENTIFICATION.VARIABLES.STATUS",
                "value":"ERROR: EVENT_EXECUTION_DENIED",
                "type":"STRING"
            },
            {
                "key":"GBCONNECT.ACCOUNT.STATEMENTS.STATUS",
                "value":"IGNORED",
                "type":"STRING"
            }
        ]
    },
    "identity":{},
    "auth":{},
    "metadata":{}
}
```

Como no primeiro erro já abortamos as futures, não teriamos uma resposta para retornar para o cliente. Utilizando essa abordagem mantemos compatibilidade com o objeto acordado, e mais consistente do que retornar ora um objeto ora outro. Mas ponto negativo seria a necessidade de percorrer o objeto para localizar onde o erro aconteceu, mas atualmente isso já é necessário.

---

No caso de retornar um erro de `RedirectException`, qual das abordagens seria mais viável? Gosto da possibilidade de deixar o erro e origem explicito - acredito que seria assim com redirecionamento -, mas pelo fato de variar objeto retornado não vejo como uma coisa boa.

**Comment by Cleidiano** [comment]
Acho que nesse caso devemos manter o contrato da api, utilizando então a segunda abordagem.

**Comment by Cleidiano** [comment]
Analisando os conceitos do connector, parece uma melhor abordagem mudar de direção no sentido de que, ao invés de introduzirmos mais uma configuração sobre um novo conceito, deveríamos aplica à um conceito que já existe que é:  evento de **`user`** e evento de **`partner`**.

Tudo que foi discutido como precendência continua igual, o que mudaria seria o escopo onde essa config vai ser aplicada que agora para a ser sobre o tipo(user/partner), então ficaria: `REDIRECT_ON_UNAUTHORIZED=NEVER|ALWAYS|USER_EVENTS|PARTNER_EVENTS`.

**Comment by jabolina** [comment]
Valeu!

![Homem-Aranha andando de skate e confirmando com a cabeca](https://media.giphy.com/media/XuGV2RvBbZVUA/giphy.gif)
